
/**
* _BanqueStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* samedi 20 novembre 2021 22 h 38 GMT+01:00
*/

public class _BanqueStub extends org.omg.CORBA.portable.ObjectImpl implements Banque
{

  public float crediter (float montant, org.omg.CORBA.FloatHolder solde)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("crediter", true);
                $out.write_float (montant);
                $in = _invoke ($out);
                float $result = $in.read_float ();
                solde.value = $in.read_float ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return crediter (montant, solde        );
            } finally {
                _releaseReply ($in);
            }
  } // crediter

  public float debiter (float montant, org.omg.CORBA.FloatHolder solde)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("debiter", true);
                $out.write_float (montant);
                $in = _invoke ($out);
                float $result = $in.read_float ();
                solde.value = $in.read_float ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return debiter (montant, solde        );
            } finally {
                _releaseReply ($in);
            }
  } // debiter

  public float afficherMontant (org.omg.CORBA.FloatHolder solde)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("afficherMontant", true);
                $in = _invoke ($out);
                float $result = $in.read_float ();
                solde.value = $in.read_float ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return afficherMontant (solde        );
            } finally {
                _releaseReply ($in);
            }
  } // afficherMontant

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Banque:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _BanqueStub
