
/**
* BanqueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* samedi 20 novembre 2021 22 h 38 GMT+01:00
*/

public interface BanqueOperations 
{
  float crediter (float montant, org.omg.CORBA.FloatHolder solde);
  float debiter (float montant, org.omg.CORBA.FloatHolder solde);
  float afficherMontant (org.omg.CORBA.FloatHolder solde);
} // interface BanqueOperations
