
/**
* BanquePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* samedi 20 novembre 2021 22 h 38 GMT+01:00
*/

public abstract class BanquePOA extends org.omg.PortableServer.Servant
 implements BanqueOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("crediter", new java.lang.Integer (0));
    _methods.put ("debiter", new java.lang.Integer (1));
    _methods.put ("afficherMontant", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Banque/crediter
       {
         float montant = in.read_float ();
         org.omg.CORBA.FloatHolder solde = new org.omg.CORBA.FloatHolder ();
         float $result = (float)0;
         $result = this.crediter (montant, solde);
         out = $rh.createReply();
         out.write_float ($result);
         out.write_float (solde.value);
         break;
       }

       case 1:  // Banque/debiter
       {
         float montant = in.read_float ();
         org.omg.CORBA.FloatHolder solde = new org.omg.CORBA.FloatHolder ();
         float $result = (float)0;
         $result = this.debiter (montant, solde);
         out = $rh.createReply();
         out.write_float ($result);
         out.write_float (solde.value);
         break;
       }

       case 2:  // Banque/afficherMontant
       {
         org.omg.CORBA.FloatHolder solde = new org.omg.CORBA.FloatHolder ();
         float $result = (float)0;
         $result = this.afficherMontant (solde);
         out = $rh.createReply();
         out.write_float ($result);
         out.write_float (solde.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Banque:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Banque _this() 
  {
    return BanqueHelper.narrow(
    super._this_object());
  }

  public Banque _this(org.omg.CORBA.ORB orb) 
  {
    return BanqueHelper.narrow(
    super._this_object(orb));
  }


} // class BanquePOA
