
/**
* Banque.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* samedi 20 novembre 2021 22 h 38 GMT+01:00
*/

public interface Banque extends BanqueOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Banque
